### ISSUE TITLE
Tooltip size not following scaling

### ISSUE THREAD

**Issue by dr0biwan** [0x5066/WinampModernForked#2]
From https://www.reddit.com/r/winamp/comments/pi03e2/too_frickin_tiny/ I though I'd give the tooltip related modifications from here a go as I wasn't sure if it'd now be matching the skin scaling options or not.

There seems to be a getScale() that can be called on a layer object (not sure about other objects) so that might be something that can be used within the tooltips script to adjust the scaling as needed. I've not dug into what's going on so I might've missed something that can do it in a cleaner way than my first thought about this.

One other thing, it might be nicer to have it accept the height being passed on the script call so it's not fixed to a size without having to recompile it (just thinking from a reusability view point :) ).

-dro

![cropped_small_tooltips_from_reddit](https://user-images.githubusercontent.com/6472795/132110340-ace42cae-17c3-410a-8bcf-4269d5b70f08.png)

**Comment by 0x5066** [comment]
Well, it's a whole lot more complicated than I thought.

It seems that getScale() can only really work on a layout to determine what the current scaling is (which returns 1.25 if the window is set to scale to 125% and so on), the issue however is telling the tooltip script that information and I'm stuck on finding a way to do it in a clean way.

The tooltip script relies on getScriptGroup(), which makes it difficult to include anywhere else (probably the intention, heh).

I wrote a test script to determine what getScale() really returns to make things easier, once that's done I decided to include that script into the tooltip script, which breaks things.

(Note: layoutscale is a global value which is inherited from scaletest.m, which also displays 1.000 in the middle of the vis display)
This is with including the test script:
![image](https://user-images.githubusercontent.com/38136789/132112101-3c500a9d-a0c7-43bd-a657-5e513ec4981c.png)

And this is without:
![image](https://user-images.githubusercontent.com/38136789/132112115-bebd49f0-a057-4dcc-b4f8-71d642ef6b58.png)

I'm at a bit of a loss of what's going on and how I can prevent the two scripts clashing with one another, but I feel like I'm close to the solution...

**Comment by 0x5066** [comment]
![image](https://user-images.githubusercontent.com/38136789/132113064-e6e7e4ab-7383-4785-9b71-bbac50c05b1e.png)
Well, I must admit defeat for now.

It seems that, even if the other script has nothing going on inside of it, the tooltip will mess up regardless and I can't get it to recognize that `layoutscale` changed, even though the text object I put inside of the display for debugging will update itself accordingly.

I will still keep this issue open regardless should something change about this, but for the moment I'm simply confused about what's happening and why things fail.

**Comment by 0x5066** [comment]
I've had another pair of eyes look at what I was attempting to do (aka asking @mirzi1 for help) and it's now fixed!

![cquGUOGknE](https://user-images.githubusercontent.com/38136789/132134820-d5bd32c9-c18b-4625-9f94-6977f8d27b9f.gif)

**Comment by dr0biwan** [comment]
Can confirm the change appears to work as expected, thank you both of you 👍

-dro
